dataset: cifar100
data_path: /home/wangjunjie/dataset
num_classes: 100
img_size: 32
noise_ratio: 0.2
partial_rate: 0.5
partial_type: hierarchical

model: resnet18
lr: 0.1
momentum: 0.9
weight_decay: 0.0005
batch_size: 128
epochs: 300
average_entropy_loss: True
noise_matrix_scale: 1.0
vol_lambda: 0.01

alpha: 2
beta: 300
lam: 1.0
lam_consist: 3
balance_lam: 0.1
beta_up: False

seed: 42
wandb: False
